version: '3.8'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: doni
      POSTGRES_PASSWORD: DoniLite13
      POSTGRES_DB: ghostifyDB
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doni"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghostify
    environment:
      DATABASE_URL: postgresql://doni:DoniLite13@localhost:5432/ghostifyDB?schema=public&connection_limit=5
      env_file: '.env'
    ports:
      - "3081:3081"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: ["pnpm", "start"]

volumes:
  db-data:


