name: Deno CD/CI Workflow
run-name: ${{ github.actor }}'s Deno CI/CD Pipeline

env:
  DENO_DIR: ~/.cache/deno

on:
  push:
    branches:
      - main
      - develop
      - 'releases/**'
    tags:
      - v2
      - 'v1.*'
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '30 5 * * 1-4' # Runs at 05:30 AM Mon-Thu

jobs:
  deno-backend-ci:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: ['2.x']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup and Install
        uses: ./.github/actions/setup-install

      - name: Generate Prisma Types
        run: bun run prisma:generate

      - name: Lint Code
        run: bun run lint

      - name: Run Tests
        run: bun test

      - name: Build Project
        run: bun run build:preview

      - name: Prepare Artifacts
        run: mkdir -p dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghostify-client-preview
          path: dist/
          retention-days: 1

  deploy-preview:
    name: Deploy Preview
    needs: deno-backend-ci
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ghostify-client-preview
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: ghostify-preview
