name: Build NodeJS CD/CI
run-name: ${{ github.actor }}'s GitHub Actions
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on: 
  push:
    branches:    
      - main
      - 'octocat/**'
      - 'releases/**'
      - develop
    tags:        
      - v2
      - v1.*
  pull_request:
    branches:    
      - main
      - 'octocat/**'
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: npm install -g bats
      - run: bats -v
      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install
      - name: Lint Code
        run: pnpm lint
      - name: Run Tests
        run: pnpm test
      - name: Build Project
        run: pnpm exec tsc --outDir build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
