name: Ghostify fullstack CI/CD
env:
  DENO_DIR: ~/.cache/deno

on:
  push:
    branches: ['main', 'develop', 'releases/**']
  pull_request:
    branches: ['main', 'develop', 'releases/**']

jobs:
  test-typescript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup and Install
        uses: ./.github/actions/setup-install

      - name: Lint TypeScript
        run: |
          bun run lint

      - name: Run TypeScript tests
        run: |
          bun test
