name: Ghostify Preview Deployment

on:
  workflow_run:
    workflows: ["Deno CD/CI Workflow"]
    types:
      - completed
    branches:
      - main
      - develop

jobs:
  check_workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - name: Check workflow status
        id: check
        run: |
          echo "Previous workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "Previous workflow did not succeed"
            exit 1
          fi

  deploy-preview:
    needs: check_workflow
    runs-on: ubuntu-latest
    if: ${{ needs.check_workflow.outputs.should_deploy == 'true' }}

    permissions:
      contents: read
      pages: write
      id-token: write
      actions: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: ghostify-client-preview
          path: ./dist
          run-id: ${{ github.event.workflow_run.id }}

      - name: List downloaded files (debug)
        run: |
          echo "Contents of dist directory:"
          ls -la ./dist/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4